# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "fix-flaky" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    
    - name: Compile the code
      run: mvn clean install -DskipTests -pl core -am

    - name: Run specific test case using maven
      run: mvn -pl core test -Dtest=org.everit.json.schema.ObjectSchemaTest#toStringNoExplicitType

    - name: Run the specific test case using the nondex tool
      run: mvn -pl core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.everit.json.schema.ObjectSchemaTest#toStringNoExplicitType
    
    
